// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gamecontroller/ssl_gc_rcon_autoref.proto

package gamecontroller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AutoRefRegistration is the first message that a client must send to the controller to identify itself
type AutoRefRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identifier is a unique name of the client
	Identifier *string `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	// signature can optionally be specified to enable secure communication
	Signature     *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRefRegistration) Reset() {
	*x = AutoRefRegistration{}
	mi := &file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRefRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRefRegistration) ProtoMessage() {}

func (x *AutoRefRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRefRegistration.ProtoReflect.Descriptor instead.
func (*AutoRefRegistration) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescGZIP(), []int{0}
}

func (x *AutoRefRegistration) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

func (x *AutoRefRegistration) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// AutoRefToController is the wrapper message for all subsequent messages from the autoRef to the controller
type AutoRefToController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signature can optionally be specified to enable secure communication
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	// game_event is an optional event that the autoRef detected during the game
	GameEvent     *GameEvent `protobuf:"bytes,2,opt,name=game_event,json=gameEvent" json:"game_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRefToController) Reset() {
	*x = AutoRefToController{}
	mi := &file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRefToController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRefToController) ProtoMessage() {}

func (x *AutoRefToController) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRefToController.ProtoReflect.Descriptor instead.
func (*AutoRefToController) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescGZIP(), []int{1}
}

func (x *AutoRefToController) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AutoRefToController) GetGameEvent() *GameEvent {
	if x != nil {
		return x.GameEvent
	}
	return nil
}

// ControllerToAutoRef is the wrapper message for all messages from controller to autoRef
type ControllerToAutoRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControllerToAutoRef_ControllerReply
	Msg           isControllerToAutoRef_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerToAutoRef) Reset() {
	*x = ControllerToAutoRef{}
	mi := &file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerToAutoRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerToAutoRef) ProtoMessage() {}

func (x *ControllerToAutoRef) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerToAutoRef.ProtoReflect.Descriptor instead.
func (*ControllerToAutoRef) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerToAutoRef) GetMsg() isControllerToAutoRef_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControllerToAutoRef) GetControllerReply() *ControllerReply {
	if x != nil {
		if x, ok := x.Msg.(*ControllerToAutoRef_ControllerReply); ok {
			return x.ControllerReply
		}
	}
	return nil
}

type isControllerToAutoRef_Msg interface {
	isControllerToAutoRef_Msg()
}

type ControllerToAutoRef_ControllerReply struct {
	// a reply from the controller
	ControllerReply *ControllerReply `protobuf:"bytes,1,opt,name=controller_reply,json=controllerReply,oneof"`
}

func (*ControllerToAutoRef_ControllerReply) isControllerToAutoRef_Msg() {}

var File_gamecontroller_ssl_gc_rcon_autoref_proto protoreflect.FileDescriptor

const file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDesc = "" +
	"\n" +
	"(gamecontroller/ssl_gc_rcon_autoref.proto\x1a&gamecontroller/ssl_gc_game_event.proto\x1a gamecontroller/ssl_gc_rcon.proto\"_\n" +
	"\x13AutoRefRegistration\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x02(\tR\n" +
	"identifier\x12(\n" +
	"\tsignature\x18\x02 \x01(\v2\n" +
	".SignatureR\tsignature\"v\n" +
	"\x13AutoRefToController\x12(\n" +
	"\tsignature\x18\x01 \x01(\v2\n" +
	".SignatureR\tsignature\x12)\n" +
	"\n" +
	"game_event\x18\x02 \x01(\v2\n" +
	".GameEventR\tgameEventJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"[\n" +
	"\x13ControllerToAutoRef\x12=\n" +
	"\x10controller_reply\x18\x01 \x01(\v2\x10.ControllerReplyH\x00R\x0fcontrollerReplyB\x05\n" +
	"\x03msgBbB\x15SslGcRconAutorefProtoP\x01ZGgithub.com/RoboCup-SSL/ssl-vision-processor/gui/internal/gamecontroller"

var (
	file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescOnce sync.Once
	file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescData []byte
)

func file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescGZIP() []byte {
	file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescOnce.Do(func() {
		file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDesc)))
	})
	return file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDescData
}

var file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gamecontroller_ssl_gc_rcon_autoref_proto_goTypes = []any{
	(*AutoRefRegistration)(nil), // 0: AutoRefRegistration
	(*AutoRefToController)(nil), // 1: AutoRefToController
	(*ControllerToAutoRef)(nil), // 2: ControllerToAutoRef
	(*Signature)(nil),           // 3: Signature
	(*GameEvent)(nil),           // 4: GameEvent
	(*ControllerReply)(nil),     // 5: ControllerReply
}
var file_gamecontroller_ssl_gc_rcon_autoref_proto_depIdxs = []int32{
	3, // 0: AutoRefRegistration.signature:type_name -> Signature
	3, // 1: AutoRefToController.signature:type_name -> Signature
	4, // 2: AutoRefToController.game_event:type_name -> GameEvent
	5, // 3: ControllerToAutoRef.controller_reply:type_name -> ControllerReply
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gamecontroller_ssl_gc_rcon_autoref_proto_init() }
func file_gamecontroller_ssl_gc_rcon_autoref_proto_init() {
	if File_gamecontroller_ssl_gc_rcon_autoref_proto != nil {
		return
	}
	file_gamecontroller_ssl_gc_game_event_proto_init()
	file_gamecontroller_ssl_gc_rcon_proto_init()
	file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes[2].OneofWrappers = []any{
		(*ControllerToAutoRef_ControllerReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_autoref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamecontroller_ssl_gc_rcon_autoref_proto_goTypes,
		DependencyIndexes: file_gamecontroller_ssl_gc_rcon_autoref_proto_depIdxs,
		MessageInfos:      file_gamecontroller_ssl_gc_rcon_autoref_proto_msgTypes,
	}.Build()
	File_gamecontroller_ssl_gc_rcon_autoref_proto = out.File
	file_gamecontroller_ssl_gc_rcon_autoref_proto_goTypes = nil
	file_gamecontroller_ssl_gc_rcon_autoref_proto_depIdxs = nil
}
