// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gamecontroller/ssl_gc_rcon_team.proto

package gamecontroller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// the current advantage choice of the team
// the choice is valid until another choice is received
// if the team disconnects, the choice is reset to its default (STOP)
// teams may either send their current choice continuously or only on change
type AdvantageChoice int32

const (
	// stop the game
	AdvantageChoice_STOP AdvantageChoice = 0
	// keep the game running
	AdvantageChoice_CONTINUE AdvantageChoice = 1
)

// Enum value maps for AdvantageChoice.
var (
	AdvantageChoice_name = map[int32]string{
		0: "STOP",
		1: "CONTINUE",
	}
	AdvantageChoice_value = map[string]int32{
		"STOP":     0,
		"CONTINUE": 1,
	}
)

func (x AdvantageChoice) Enum() *AdvantageChoice {
	p := new(AdvantageChoice)
	*p = x
	return p
}

func (x AdvantageChoice) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdvantageChoice) Descriptor() protoreflect.EnumDescriptor {
	return file_gamecontroller_ssl_gc_rcon_team_proto_enumTypes[0].Descriptor()
}

func (AdvantageChoice) Type() protoreflect.EnumType {
	return &file_gamecontroller_ssl_gc_rcon_team_proto_enumTypes[0]
}

func (x AdvantageChoice) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AdvantageChoice) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AdvantageChoice(num)
	return nil
}

// Deprecated: Use AdvantageChoice.Descriptor instead.
func (AdvantageChoice) EnumDescriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_team_proto_rawDescGZIP(), []int{0}
}

// a registration that must be send by teams to the controller as the very first message
type TeamRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the exact team name as published by the game-controller
	TeamName *string `protobuf:"bytes,1,req,name=team_name,json=teamName" json:"team_name,omitempty"`
	// signature can optionally be specified to enable secure communication
	Signature *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	// the team (relevant only if a team plays against itself)
	Team          *Team `protobuf:"varint,3,opt,name=team,enum=Team" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamRegistration) Reset() {
	*x = TeamRegistration{}
	mi := &file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamRegistration) ProtoMessage() {}

func (x *TeamRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamRegistration.ProtoReflect.Descriptor instead.
func (*TeamRegistration) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_team_proto_rawDescGZIP(), []int{0}
}

func (x *TeamRegistration) GetTeamName() string {
	if x != nil && x.TeamName != nil {
		return *x.TeamName
	}
	return ""
}

func (x *TeamRegistration) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TeamRegistration) GetTeam() Team {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return Team_UNKNOWN
}

// wrapper for all messages from a team's computer to the controller
type TeamToController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signature can optionally be specified to enable secure communication
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*TeamToController_DesiredKeeper
	//	*TeamToController_AdvantageChoice
	//	*TeamToController_SubstituteBot
	//	*TeamToController_Ping
	Msg           isTeamToController_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamToController) Reset() {
	*x = TeamToController{}
	mi := &file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamToController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamToController) ProtoMessage() {}

func (x *TeamToController) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamToController.ProtoReflect.Descriptor instead.
func (*TeamToController) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_team_proto_rawDescGZIP(), []int{1}
}

func (x *TeamToController) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TeamToController) GetMsg() isTeamToController_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *TeamToController) GetDesiredKeeper() int32 {
	if x != nil {
		if x, ok := x.Msg.(*TeamToController_DesiredKeeper); ok {
			return x.DesiredKeeper
		}
	}
	return 0
}

func (x *TeamToController) GetAdvantageChoice() AdvantageChoice {
	if x != nil {
		if x, ok := x.Msg.(*TeamToController_AdvantageChoice); ok {
			return x.AdvantageChoice
		}
	}
	return AdvantageChoice_STOP
}

func (x *TeamToController) GetSubstituteBot() bool {
	if x != nil {
		if x, ok := x.Msg.(*TeamToController_SubstituteBot); ok {
			return x.SubstituteBot
		}
	}
	return false
}

func (x *TeamToController) GetPing() bool {
	if x != nil {
		if x, ok := x.Msg.(*TeamToController_Ping); ok {
			return x.Ping
		}
	}
	return false
}

type isTeamToController_Msg interface {
	isTeamToController_Msg()
}

type TeamToController_DesiredKeeper struct {
	// request a new desired keeper id
	DesiredKeeper int32 `protobuf:"varint,2,opt,name=desired_keeper,json=desiredKeeper,oneof"`
}

type TeamToController_AdvantageChoice struct {
	// response to an advantage choice request
	AdvantageChoice AdvantageChoice `protobuf:"varint,3,opt,name=advantage_choice,json=advantageChoice,enum=AdvantageChoice,oneof"`
}

type TeamToController_SubstituteBot struct {
	// request to substitute a robot at the next possibility
	SubstituteBot bool `protobuf:"varint,4,opt,name=substitute_bot,json=substituteBot,oneof"`
}

type TeamToController_Ping struct {
	// send a ping to the GC to test if the connection is still open.
	// the value is ignored and a reply is sent back
	Ping bool `protobuf:"varint,5,opt,name=ping,oneof"`
}

func (*TeamToController_DesiredKeeper) isTeamToController_Msg() {}

func (*TeamToController_AdvantageChoice) isTeamToController_Msg() {}

func (*TeamToController_SubstituteBot) isTeamToController_Msg() {}

func (*TeamToController_Ping) isTeamToController_Msg() {}

// wrapper for all messages from controller to a team's computer
type ControllerToTeam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControllerToTeam_ControllerReply
	Msg           isControllerToTeam_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerToTeam) Reset() {
	*x = ControllerToTeam{}
	mi := &file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerToTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerToTeam) ProtoMessage() {}

func (x *ControllerToTeam) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerToTeam.ProtoReflect.Descriptor instead.
func (*ControllerToTeam) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_team_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerToTeam) GetMsg() isControllerToTeam_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControllerToTeam) GetControllerReply() *ControllerReply {
	if x != nil {
		if x, ok := x.Msg.(*ControllerToTeam_ControllerReply); ok {
			return x.ControllerReply
		}
	}
	return nil
}

type isControllerToTeam_Msg interface {
	isControllerToTeam_Msg()
}

type ControllerToTeam_ControllerReply struct {
	// a reply from the controller
	ControllerReply *ControllerReply `protobuf:"bytes,1,opt,name=controller_reply,json=controllerReply,oneof"`
}

func (*ControllerToTeam_ControllerReply) isControllerToTeam_Msg() {}

var File_gamecontroller_ssl_gc_rcon_team_proto protoreflect.FileDescriptor

const file_gamecontroller_ssl_gc_rcon_team_proto_rawDesc = "" +
	"\n" +
	"%gamecontroller/ssl_gc_rcon_team.proto\x1a\"gamecontroller/ssl_gc_common.proto\x1a gamecontroller/ssl_gc_rcon.proto\"t\n" +
	"\x10TeamRegistration\x12\x1b\n" +
	"\tteam_name\x18\x01 \x02(\tR\bteamName\x12(\n" +
	"\tsignature\x18\x02 \x01(\v2\n" +
	".SignatureR\tsignature\x12\x19\n" +
	"\x04team\x18\x03 \x01(\x0e2\x05.TeamR\x04team\"\xea\x01\n" +
	"\x10TeamToController\x12(\n" +
	"\tsignature\x18\x01 \x01(\v2\n" +
	".SignatureR\tsignature\x12'\n" +
	"\x0edesired_keeper\x18\x02 \x01(\x05H\x00R\rdesiredKeeper\x12=\n" +
	"\x10advantage_choice\x18\x03 \x01(\x0e2\x10.AdvantageChoiceH\x00R\x0fadvantageChoice\x12'\n" +
	"\x0esubstitute_bot\x18\x04 \x01(\bH\x00R\rsubstituteBot\x12\x14\n" +
	"\x04ping\x18\x05 \x01(\bH\x00R\x04pingB\x05\n" +
	"\x03msg\"^\n" +
	"\x10ControllerToTeam\x12=\n" +
	"\x10controller_reply\x18\x01 \x01(\v2\x10.ControllerReplyH\x00R\x0fcontrollerReplyB\x05\n" +
	"\x03msgJ\x04\b\x02\x10\x03*)\n" +
	"\x0fAdvantageChoice\x12\b\n" +
	"\x04STOP\x10\x00\x12\f\n" +
	"\bCONTINUE\x10\x01B_B\x12SslGcRconTeamProtoP\x01ZGgithub.com/RoboCup-SSL/ssl-vision-processor/gui/internal/gamecontroller"

var (
	file_gamecontroller_ssl_gc_rcon_team_proto_rawDescOnce sync.Once
	file_gamecontroller_ssl_gc_rcon_team_proto_rawDescData []byte
)

func file_gamecontroller_ssl_gc_rcon_team_proto_rawDescGZIP() []byte {
	file_gamecontroller_ssl_gc_rcon_team_proto_rawDescOnce.Do(func() {
		file_gamecontroller_ssl_gc_rcon_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_team_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_team_proto_rawDesc)))
	})
	return file_gamecontroller_ssl_gc_rcon_team_proto_rawDescData
}

var file_gamecontroller_ssl_gc_rcon_team_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gamecontroller_ssl_gc_rcon_team_proto_goTypes = []any{
	(AdvantageChoice)(0),     // 0: AdvantageChoice
	(*TeamRegistration)(nil), // 1: TeamRegistration
	(*TeamToController)(nil), // 2: TeamToController
	(*ControllerToTeam)(nil), // 3: ControllerToTeam
	(*Signature)(nil),        // 4: Signature
	(Team)(0),                // 5: Team
	(*ControllerReply)(nil),  // 6: ControllerReply
}
var file_gamecontroller_ssl_gc_rcon_team_proto_depIdxs = []int32{
	4, // 0: TeamRegistration.signature:type_name -> Signature
	5, // 1: TeamRegistration.team:type_name -> Team
	4, // 2: TeamToController.signature:type_name -> Signature
	0, // 3: TeamToController.advantage_choice:type_name -> AdvantageChoice
	6, // 4: ControllerToTeam.controller_reply:type_name -> ControllerReply
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gamecontroller_ssl_gc_rcon_team_proto_init() }
func file_gamecontroller_ssl_gc_rcon_team_proto_init() {
	if File_gamecontroller_ssl_gc_rcon_team_proto != nil {
		return
	}
	file_gamecontroller_ssl_gc_common_proto_init()
	file_gamecontroller_ssl_gc_rcon_proto_init()
	file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[1].OneofWrappers = []any{
		(*TeamToController_DesiredKeeper)(nil),
		(*TeamToController_AdvantageChoice)(nil),
		(*TeamToController_SubstituteBot)(nil),
		(*TeamToController_Ping)(nil),
	}
	file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes[2].OneofWrappers = []any{
		(*ControllerToTeam_ControllerReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_team_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_team_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamecontroller_ssl_gc_rcon_team_proto_goTypes,
		DependencyIndexes: file_gamecontroller_ssl_gc_rcon_team_proto_depIdxs,
		EnumInfos:         file_gamecontroller_ssl_gc_rcon_team_proto_enumTypes,
		MessageInfos:      file_gamecontroller_ssl_gc_rcon_team_proto_msgTypes,
	}.Build()
	File_gamecontroller_ssl_gc_rcon_team_proto = out.File
	file_gamecontroller_ssl_gc_rcon_team_proto_goTypes = nil
	file_gamecontroller_ssl_gc_rcon_team_proto_depIdxs = nil
}
