// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gamecontroller/ssl_gc_rcon_remotecontrol.proto

package gamecontroller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All possible request types that the remote control can make
type RemoteControlRequestType int32

const (
	RemoteControlRequestType_UNKNOWN_REQUEST_TYPE RemoteControlRequestType = 0
	RemoteControlRequestType_EMERGENCY_STOP       RemoteControlRequestType = 1
	RemoteControlRequestType_ROBOT_SUBSTITUTION   RemoteControlRequestType = 2
	RemoteControlRequestType_TIMEOUT              RemoteControlRequestType = 3
	RemoteControlRequestType_CHALLENGE_FLAG       RemoteControlRequestType = 4
	RemoteControlRequestType_CHANGE_KEEPER_ID     RemoteControlRequestType = 5
	RemoteControlRequestType_STOP_TIMEOUT         RemoteControlRequestType = 6
	RemoteControlRequestType_FAIL_BALLPLACEMENT   RemoteControlRequestType = 7
)

// Enum value maps for RemoteControlRequestType.
var (
	RemoteControlRequestType_name = map[int32]string{
		0: "UNKNOWN_REQUEST_TYPE",
		1: "EMERGENCY_STOP",
		2: "ROBOT_SUBSTITUTION",
		3: "TIMEOUT",
		4: "CHALLENGE_FLAG",
		5: "CHANGE_KEEPER_ID",
		6: "STOP_TIMEOUT",
		7: "FAIL_BALLPLACEMENT",
	}
	RemoteControlRequestType_value = map[string]int32{
		"UNKNOWN_REQUEST_TYPE": 0,
		"EMERGENCY_STOP":       1,
		"ROBOT_SUBSTITUTION":   2,
		"TIMEOUT":              3,
		"CHALLENGE_FLAG":       4,
		"CHANGE_KEEPER_ID":     5,
		"STOP_TIMEOUT":         6,
		"FAIL_BALLPLACEMENT":   7,
	}
)

func (x RemoteControlRequestType) Enum() *RemoteControlRequestType {
	p := new(RemoteControlRequestType)
	*p = x
	return p
}

func (x RemoteControlRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteControlRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_enumTypes[0].Descriptor()
}

func (RemoteControlRequestType) Type() protoreflect.EnumType {
	return &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_enumTypes[0]
}

func (x RemoteControlRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RemoteControlRequestType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RemoteControlRequestType(num)
	return nil
}

// Deprecated: Use RemoteControlRequestType.Descriptor instead.
func (RemoteControlRequestType) EnumDescriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP(), []int{0}
}

type RemoteControlToController_Request int32

const (
	RemoteControlToController_UNKNOWN RemoteControlToController_Request = 0
	// Ping the GC to test the connection. The GC will respond with OK and the current team state
	RemoteControlToController_PING RemoteControlToController_Request = 1
	// Raise a challenge flag (this is not revocable)
	RemoteControlToController_CHALLENGE_FLAG RemoteControlToController_Request = 2
	// Stop an ongoing timeout
	RemoteControlToController_STOP_TIMEOUT RemoteControlToController_Request = 3
	// Fail a ball placement
	RemoteControlToController_FAIL_BALLPLACEMENT RemoteControlToController_Request = 4
)

// Enum value maps for RemoteControlToController_Request.
var (
	RemoteControlToController_Request_name = map[int32]string{
		0: "UNKNOWN",
		1: "PING",
		2: "CHALLENGE_FLAG",
		3: "STOP_TIMEOUT",
		4: "FAIL_BALLPLACEMENT",
	}
	RemoteControlToController_Request_value = map[string]int32{
		"UNKNOWN":            0,
		"PING":               1,
		"CHALLENGE_FLAG":     2,
		"STOP_TIMEOUT":       3,
		"FAIL_BALLPLACEMENT": 4,
	}
)

func (x RemoteControlToController_Request) Enum() *RemoteControlToController_Request {
	p := new(RemoteControlToController_Request)
	*p = x
	return p
}

func (x RemoteControlToController_Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteControlToController_Request) Descriptor() protoreflect.EnumDescriptor {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_enumTypes[1].Descriptor()
}

func (RemoteControlToController_Request) Type() protoreflect.EnumType {
	return &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_enumTypes[1]
}

func (x RemoteControlToController_Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RemoteControlToController_Request) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RemoteControlToController_Request(num)
	return nil
}

// Deprecated: Use RemoteControlToController_Request.Descriptor instead.
func (RemoteControlToController_Request) EnumDescriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP(), []int{1, 0}
}

// a registration that must be send by the remote control to the controller as the very first message
type RemoteControlRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the team to be controlled
	Team *Team `protobuf:"varint,1,req,name=team,enum=Team" json:"team,omitempty"`
	// signature can optionally be specified to enable secure communication
	Signature     *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteControlRegistration) Reset() {
	*x = RemoteControlRegistration{}
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteControlRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControlRegistration) ProtoMessage() {}

func (x *RemoteControlRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControlRegistration.ProtoReflect.Descriptor instead.
func (*RemoteControlRegistration) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteControlRegistration) GetTeam() Team {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return Team_UNKNOWN
}

func (x *RemoteControlRegistration) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// wrapper for all messages from the remote control to the controller
type RemoteControlToController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signature can optionally be specified to enable secure communication
	Signature *Signature `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RemoteControlToController_Request_
	//	*RemoteControlToController_DesiredKeeper
	//	*RemoteControlToController_RequestRobotSubstitution
	//	*RemoteControlToController_RequestTimeout
	//	*RemoteControlToController_RequestEmergencyStop
	Msg           isRemoteControlToController_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteControlToController) Reset() {
	*x = RemoteControlToController{}
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteControlToController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControlToController) ProtoMessage() {}

func (x *RemoteControlToController) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControlToController.ProtoReflect.Descriptor instead.
func (*RemoteControlToController) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteControlToController) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RemoteControlToController) GetMsg() isRemoteControlToController_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RemoteControlToController) GetRequest() RemoteControlToController_Request {
	if x != nil {
		if x, ok := x.Msg.(*RemoteControlToController_Request_); ok {
			return x.Request
		}
	}
	return RemoteControlToController_UNKNOWN
}

func (x *RemoteControlToController) GetDesiredKeeper() int32 {
	if x != nil {
		if x, ok := x.Msg.(*RemoteControlToController_DesiredKeeper); ok {
			return x.DesiredKeeper
		}
	}
	return 0
}

func (x *RemoteControlToController) GetRequestRobotSubstitution() bool {
	if x != nil {
		if x, ok := x.Msg.(*RemoteControlToController_RequestRobotSubstitution); ok {
			return x.RequestRobotSubstitution
		}
	}
	return false
}

func (x *RemoteControlToController) GetRequestTimeout() bool {
	if x != nil {
		if x, ok := x.Msg.(*RemoteControlToController_RequestTimeout); ok {
			return x.RequestTimeout
		}
	}
	return false
}

func (x *RemoteControlToController) GetRequestEmergencyStop() bool {
	if x != nil {
		if x, ok := x.Msg.(*RemoteControlToController_RequestEmergencyStop); ok {
			return x.RequestEmergencyStop
		}
	}
	return false
}

type isRemoteControlToController_Msg interface {
	isRemoteControlToController_Msg()
}

type RemoteControlToController_Request_ struct {
	// send a request to the GC
	Request RemoteControlToController_Request `protobuf:"varint,2,opt,name=request,enum=RemoteControlToController_Request,oneof"`
}

type RemoteControlToController_DesiredKeeper struct {
	// request a new desired keeper id
	DesiredKeeper int32 `protobuf:"varint,3,opt,name=desired_keeper,json=desiredKeeper,oneof"`
}

type RemoteControlToController_RequestRobotSubstitution struct {
	// true: request to substitute a robot at the next possibility
	// false: cancel request
	RequestRobotSubstitution bool `protobuf:"varint,4,opt,name=request_robot_substitution,json=requestRobotSubstitution,oneof"`
}

type RemoteControlToController_RequestTimeout struct {
	// true: request a timeout with the next stoppage
	// false: cancel the request
	RequestTimeout bool `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,oneof"`
}

type RemoteControlToController_RequestEmergencyStop struct {
	// true: initiate an emergency stop
	// false: cancel the request
	RequestEmergencyStop bool `protobuf:"varint,6,opt,name=request_emergency_stop,json=requestEmergencyStop,oneof"`
}

func (*RemoteControlToController_Request_) isRemoteControlToController_Msg() {}

func (*RemoteControlToController_DesiredKeeper) isRemoteControlToController_Msg() {}

func (*RemoteControlToController_RequestRobotSubstitution) isRemoteControlToController_Msg() {}

func (*RemoteControlToController_RequestTimeout) isRemoteControlToController_Msg() {}

func (*RemoteControlToController_RequestEmergencyStop) isRemoteControlToController_Msg() {}

// wrapper for all messages from controller to a team's computer
type ControllerToRemoteControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// a reply from the controller
	ControllerReply *ControllerReply `protobuf:"bytes,1,opt,name=controller_reply,json=controllerReply" json:"controller_reply,omitempty"`
	// current team state
	State         *RemoteControlTeamState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerToRemoteControl) Reset() {
	*x = ControllerToRemoteControl{}
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerToRemoteControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerToRemoteControl) ProtoMessage() {}

func (x *ControllerToRemoteControl) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerToRemoteControl.ProtoReflect.Descriptor instead.
func (*ControllerToRemoteControl) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerToRemoteControl) GetControllerReply() *ControllerReply {
	if x != nil {
		return x.ControllerReply
	}
	return nil
}

func (x *ControllerToRemoteControl) GetState() *RemoteControlTeamState {
	if x != nil {
		return x.State
	}
	return nil
}

// Current team state from Controller for remote control
type RemoteControlTeamState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the team that is controlled
	Team *Team `protobuf:"varint,12,opt,name=team,enum=Team" json:"team,omitempty"`
	// list of all currently available request types that can be made
	AvailableRequests []RemoteControlRequestType `protobuf:"varint,1,rep,name=available_requests,json=availableRequests,enum=RemoteControlRequestType" json:"available_requests,omitempty"`
	// list of all currently active request types that are pending
	ActiveRequests []RemoteControlRequestType `protobuf:"varint,2,rep,name=active_requests,json=activeRequests,enum=RemoteControlRequestType" json:"active_requests,omitempty"`
	// currently set keeper id
	KeeperId *int32 `protobuf:"varint,3,opt,name=keeper_id,json=keeperId" json:"keeper_id,omitempty"`
	// number of seconds till emergency stop is executed
	// zero, if no emergency stop requested
	EmergencyStopIn *float32 `protobuf:"fixed32,4,opt,name=emergency_stop_in,json=emergencyStopIn" json:"emergency_stop_in,omitempty"`
	// number of timeouts left for the team
	TimeoutsLeft *int32 `protobuf:"varint,5,opt,name=timeouts_left,json=timeoutsLeft" json:"timeouts_left,omitempty"`
	// number of seconds left for timeout for the team
	TimeoutTimeLeft *float32 `protobuf:"fixed32,10,opt,name=timeout_time_left,json=timeoutTimeLeft" json:"timeout_time_left,omitempty"`
	// number of challenge flags left for the team
	ChallengeFlagsLeft *int32 `protobuf:"varint,6,opt,name=challenge_flags_left,json=challengeFlagsLeft" json:"challenge_flags_left,omitempty"`
	// max number of robots currently allowed
	MaxRobots *int32 `protobuf:"varint,7,opt,name=max_robots,json=maxRobots" json:"max_robots,omitempty"`
	// current number of robots visible on field
	RobotsOnField *int32 `protobuf:"varint,9,opt,name=robots_on_field,json=robotsOnField" json:"robots_on_field,omitempty"`
	// list of due times for each active yellow card (in seconds)
	YellowCardsDue []float32 `protobuf:"fixed32,8,rep,name=yellow_cards_due,json=yellowCardsDue" json:"yellow_cards_due,omitempty"`
	// if true, team is allowed to substitute robots
	CanSubstituteRobot *bool `protobuf:"varint,11,opt,name=can_substitute_robot,json=canSubstituteRobot" json:"can_substitute_robot,omitempty"`
	// number of bot substitutions left by the team in this halftime
	BotSubstitutionsLeft *uint32 `protobuf:"varint,13,opt,name=bot_substitutions_left,json=botSubstitutionsLeft" json:"bot_substitutions_left,omitempty"`
	// number of seconds left for current bot substitution
	BotSubstitutionTimeLeft *float32 `protobuf:"fixed32,14,opt,name=bot_substitution_time_left,json=botSubstitutionTimeLeft" json:"bot_substitution_time_left,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RemoteControlTeamState) Reset() {
	*x = RemoteControlTeamState{}
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteControlTeamState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControlTeamState) ProtoMessage() {}

func (x *RemoteControlTeamState) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControlTeamState.ProtoReflect.Descriptor instead.
func (*RemoteControlTeamState) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteControlTeamState) GetTeam() Team {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return Team_UNKNOWN
}

func (x *RemoteControlTeamState) GetAvailableRequests() []RemoteControlRequestType {
	if x != nil {
		return x.AvailableRequests
	}
	return nil
}

func (x *RemoteControlTeamState) GetActiveRequests() []RemoteControlRequestType {
	if x != nil {
		return x.ActiveRequests
	}
	return nil
}

func (x *RemoteControlTeamState) GetKeeperId() int32 {
	if x != nil && x.KeeperId != nil {
		return *x.KeeperId
	}
	return 0
}

func (x *RemoteControlTeamState) GetEmergencyStopIn() float32 {
	if x != nil && x.EmergencyStopIn != nil {
		return *x.EmergencyStopIn
	}
	return 0
}

func (x *RemoteControlTeamState) GetTimeoutsLeft() int32 {
	if x != nil && x.TimeoutsLeft != nil {
		return *x.TimeoutsLeft
	}
	return 0
}

func (x *RemoteControlTeamState) GetTimeoutTimeLeft() float32 {
	if x != nil && x.TimeoutTimeLeft != nil {
		return *x.TimeoutTimeLeft
	}
	return 0
}

func (x *RemoteControlTeamState) GetChallengeFlagsLeft() int32 {
	if x != nil && x.ChallengeFlagsLeft != nil {
		return *x.ChallengeFlagsLeft
	}
	return 0
}

func (x *RemoteControlTeamState) GetMaxRobots() int32 {
	if x != nil && x.MaxRobots != nil {
		return *x.MaxRobots
	}
	return 0
}

func (x *RemoteControlTeamState) GetRobotsOnField() int32 {
	if x != nil && x.RobotsOnField != nil {
		return *x.RobotsOnField
	}
	return 0
}

func (x *RemoteControlTeamState) GetYellowCardsDue() []float32 {
	if x != nil {
		return x.YellowCardsDue
	}
	return nil
}

func (x *RemoteControlTeamState) GetCanSubstituteRobot() bool {
	if x != nil && x.CanSubstituteRobot != nil {
		return *x.CanSubstituteRobot
	}
	return false
}

func (x *RemoteControlTeamState) GetBotSubstitutionsLeft() uint32 {
	if x != nil && x.BotSubstitutionsLeft != nil {
		return *x.BotSubstitutionsLeft
	}
	return 0
}

func (x *RemoteControlTeamState) GetBotSubstitutionTimeLeft() float32 {
	if x != nil && x.BotSubstitutionTimeLeft != nil {
		return *x.BotSubstitutionTimeLeft
	}
	return 0
}

var File_gamecontroller_ssl_gc_rcon_remotecontrol_proto protoreflect.FileDescriptor

const file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDesc = "" +
	"\n" +
	".gamecontroller/ssl_gc_rcon_remotecontrol.proto\x1a\"gamecontroller/ssl_gc_common.proto\x1a gamecontroller/ssl_gc_rcon.proto\"`\n" +
	"\x19RemoteControlRegistration\x12\x19\n" +
	"\x04team\x18\x01 \x02(\x0e2\x05.TeamR\x04team\x12(\n" +
	"\tsignature\x18\x02 \x01(\v2\n" +
	".SignatureR\tsignature\"\xb8\x03\n" +
	"\x19RemoteControlToController\x12(\n" +
	"\tsignature\x18\x01 \x01(\v2\n" +
	".SignatureR\tsignature\x12>\n" +
	"\arequest\x18\x02 \x01(\x0e2\".RemoteControlToController.RequestH\x00R\arequest\x12'\n" +
	"\x0edesired_keeper\x18\x03 \x01(\x05H\x00R\rdesiredKeeper\x12>\n" +
	"\x1arequest_robot_substitution\x18\x04 \x01(\bH\x00R\x18requestRobotSubstitution\x12)\n" +
	"\x0frequest_timeout\x18\x05 \x01(\bH\x00R\x0erequestTimeout\x126\n" +
	"\x16request_emergency_stop\x18\x06 \x01(\bH\x00R\x14requestEmergencyStop\"^\n" +
	"\aRequest\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\x12\n" +
	"\x0eCHALLENGE_FLAG\x10\x02\x12\x10\n" +
	"\fSTOP_TIMEOUT\x10\x03\x12\x16\n" +
	"\x12FAIL_BALLPLACEMENT\x10\x04B\x05\n" +
	"\x03msg\"\x87\x01\n" +
	"\x19ControllerToRemoteControl\x12;\n" +
	"\x10controller_reply\x18\x01 \x01(\v2\x10.ControllerReplyR\x0fcontrollerReply\x12-\n" +
	"\x05state\x18\x02 \x01(\v2\x17.RemoteControlTeamStateR\x05state\"\xa3\x05\n" +
	"\x16RemoteControlTeamState\x12\x19\n" +
	"\x04team\x18\f \x01(\x0e2\x05.TeamR\x04team\x12H\n" +
	"\x12available_requests\x18\x01 \x03(\x0e2\x19.RemoteControlRequestTypeR\x11availableRequests\x12B\n" +
	"\x0factive_requests\x18\x02 \x03(\x0e2\x19.RemoteControlRequestTypeR\x0eactiveRequests\x12\x1b\n" +
	"\tkeeper_id\x18\x03 \x01(\x05R\bkeeperId\x12*\n" +
	"\x11emergency_stop_in\x18\x04 \x01(\x02R\x0femergencyStopIn\x12#\n" +
	"\rtimeouts_left\x18\x05 \x01(\x05R\ftimeoutsLeft\x12*\n" +
	"\x11timeout_time_left\x18\n" +
	" \x01(\x02R\x0ftimeoutTimeLeft\x120\n" +
	"\x14challenge_flags_left\x18\x06 \x01(\x05R\x12challengeFlagsLeft\x12\x1d\n" +
	"\n" +
	"max_robots\x18\a \x01(\x05R\tmaxRobots\x12&\n" +
	"\x0frobots_on_field\x18\t \x01(\x05R\rrobotsOnField\x12(\n" +
	"\x10yellow_cards_due\x18\b \x03(\x02R\x0eyellowCardsDue\x120\n" +
	"\x14can_substitute_robot\x18\v \x01(\bR\x12canSubstituteRobot\x124\n" +
	"\x16bot_substitutions_left\x18\r \x01(\rR\x14botSubstitutionsLeft\x12;\n" +
	"\x1abot_substitution_time_left\x18\x0e \x01(\x02R\x17botSubstitutionTimeLeft*\xc1\x01\n" +
	"\x18RemoteControlRequestType\x12\x18\n" +
	"\x14UNKNOWN_REQUEST_TYPE\x10\x00\x12\x12\n" +
	"\x0eEMERGENCY_STOP\x10\x01\x12\x16\n" +
	"\x12ROBOT_SUBSTITUTION\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\x12\x12\n" +
	"\x0eCHALLENGE_FLAG\x10\x04\x12\x14\n" +
	"\x10CHANGE_KEEPER_ID\x10\x05\x12\x10\n" +
	"\fSTOP_TIMEOUT\x10\x06\x12\x16\n" +
	"\x12FAIL_BALLPLACEMENT\x10\aBhB\x1bSslGcRconRemotecontrolProtoP\x01ZGgithub.com/RoboCup-SSL/ssl-vision-processor/gui/internal/gamecontroller"

var (
	file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescOnce sync.Once
	file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescData []byte
)

func file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescGZIP() []byte {
	file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescOnce.Do(func() {
		file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDesc)))
	})
	return file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDescData
}

var file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_goTypes = []any{
	(RemoteControlRequestType)(0),          // 0: RemoteControlRequestType
	(RemoteControlToController_Request)(0), // 1: RemoteControlToController.Request
	(*RemoteControlRegistration)(nil),      // 2: RemoteControlRegistration
	(*RemoteControlToController)(nil),      // 3: RemoteControlToController
	(*ControllerToRemoteControl)(nil),      // 4: ControllerToRemoteControl
	(*RemoteControlTeamState)(nil),         // 5: RemoteControlTeamState
	(Team)(0),                              // 6: Team
	(*Signature)(nil),                      // 7: Signature
	(*ControllerReply)(nil),                // 8: ControllerReply
}
var file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_depIdxs = []int32{
	6, // 0: RemoteControlRegistration.team:type_name -> Team
	7, // 1: RemoteControlRegistration.signature:type_name -> Signature
	7, // 2: RemoteControlToController.signature:type_name -> Signature
	1, // 3: RemoteControlToController.request:type_name -> RemoteControlToController.Request
	8, // 4: ControllerToRemoteControl.controller_reply:type_name -> ControllerReply
	5, // 5: ControllerToRemoteControl.state:type_name -> RemoteControlTeamState
	6, // 6: RemoteControlTeamState.team:type_name -> Team
	0, // 7: RemoteControlTeamState.available_requests:type_name -> RemoteControlRequestType
	0, // 8: RemoteControlTeamState.active_requests:type_name -> RemoteControlRequestType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_init() }
func file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_init() {
	if File_gamecontroller_ssl_gc_rcon_remotecontrol_proto != nil {
		return
	}
	file_gamecontroller_ssl_gc_common_proto_init()
	file_gamecontroller_ssl_gc_rcon_proto_init()
	file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes[1].OneofWrappers = []any{
		(*RemoteControlToController_Request_)(nil),
		(*RemoteControlToController_DesiredKeeper)(nil),
		(*RemoteControlToController_RequestRobotSubstitution)(nil),
		(*RemoteControlToController_RequestTimeout)(nil),
		(*RemoteControlToController_RequestEmergencyStop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_goTypes,
		DependencyIndexes: file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_depIdxs,
		EnumInfos:         file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_enumTypes,
		MessageInfos:      file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_msgTypes,
	}.Build()
	File_gamecontroller_ssl_gc_rcon_remotecontrol_proto = out.File
	file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_goTypes = nil
	file_gamecontroller_ssl_gc_rcon_remotecontrol_proto_depIdxs = nil
}
