// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gamecontroller/ssl_gc_rcon.proto

package gamecontroller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerReply_StatusCode int32

const (
	ControllerReply_UNKNOWN_STATUS_CODE ControllerReply_StatusCode = 0
	ControllerReply_OK                  ControllerReply_StatusCode = 1
	ControllerReply_REJECTED            ControllerReply_StatusCode = 2
)

// Enum value maps for ControllerReply_StatusCode.
var (
	ControllerReply_StatusCode_name = map[int32]string{
		0: "UNKNOWN_STATUS_CODE",
		1: "OK",
		2: "REJECTED",
	}
	ControllerReply_StatusCode_value = map[string]int32{
		"UNKNOWN_STATUS_CODE": 0,
		"OK":                  1,
		"REJECTED":            2,
	}
)

func (x ControllerReply_StatusCode) Enum() *ControllerReply_StatusCode {
	p := new(ControllerReply_StatusCode)
	*p = x
	return p
}

func (x ControllerReply_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerReply_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gamecontroller_ssl_gc_rcon_proto_enumTypes[0].Descriptor()
}

func (ControllerReply_StatusCode) Type() protoreflect.EnumType {
	return &file_gamecontroller_ssl_gc_rcon_proto_enumTypes[0]
}

func (x ControllerReply_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ControllerReply_StatusCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ControllerReply_StatusCode(num)
	return nil
}

// Deprecated: Use ControllerReply_StatusCode.Descriptor instead.
func (ControllerReply_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_proto_rawDescGZIP(), []int{0, 0}
}

type ControllerReply_Verification int32

const (
	ControllerReply_UNKNOWN_VERIFICATION ControllerReply_Verification = 0
	ControllerReply_VERIFIED             ControllerReply_Verification = 1
	ControllerReply_UNVERIFIED           ControllerReply_Verification = 2
)

// Enum value maps for ControllerReply_Verification.
var (
	ControllerReply_Verification_name = map[int32]string{
		0: "UNKNOWN_VERIFICATION",
		1: "VERIFIED",
		2: "UNVERIFIED",
	}
	ControllerReply_Verification_value = map[string]int32{
		"UNKNOWN_VERIFICATION": 0,
		"VERIFIED":             1,
		"UNVERIFIED":           2,
	}
)

func (x ControllerReply_Verification) Enum() *ControllerReply_Verification {
	p := new(ControllerReply_Verification)
	*p = x
	return p
}

func (x ControllerReply_Verification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerReply_Verification) Descriptor() protoreflect.EnumDescriptor {
	return file_gamecontroller_ssl_gc_rcon_proto_enumTypes[1].Descriptor()
}

func (ControllerReply_Verification) Type() protoreflect.EnumType {
	return &file_gamecontroller_ssl_gc_rcon_proto_enumTypes[1]
}

func (x ControllerReply_Verification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ControllerReply_Verification) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ControllerReply_Verification(num)
	return nil
}

// Deprecated: Use ControllerReply_Verification.Descriptor instead.
func (ControllerReply_Verification) EnumDescriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_proto_rawDescGZIP(), []int{0, 1}
}

// a reply that is sent by the controller for each request from teams or autoRefs
type ControllerReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status_code is an optional code that indicates the result of the last request
	StatusCode *ControllerReply_StatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,enum=ControllerReply_StatusCode" json:"status_code,omitempty"`
	// reason is an optional explanation of the status code
	Reason *string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	// next_token must be send with the next request, if secure communication is used
	// the token is used to avoid replay attacks
	// the token is always present in the very first message before the registration starts
	// the token is not present, if secure communication is not used
	NextToken *string `protobuf:"bytes,3,opt,name=next_token,json=nextToken" json:"next_token,omitempty"`
	// verification indicates if the last request could be verified (secure communication)
	Verification  *ControllerReply_Verification `protobuf:"varint,4,opt,name=verification,enum=ControllerReply_Verification" json:"verification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerReply) Reset() {
	*x = ControllerReply{}
	mi := &file_gamecontroller_ssl_gc_rcon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerReply) ProtoMessage() {}

func (x *ControllerReply) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerReply.ProtoReflect.Descriptor instead.
func (*ControllerReply) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_proto_rawDescGZIP(), []int{0}
}

func (x *ControllerReply) GetStatusCode() ControllerReply_StatusCode {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return ControllerReply_UNKNOWN_STATUS_CODE
}

func (x *ControllerReply) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *ControllerReply) GetNextToken() string {
	if x != nil && x.NextToken != nil {
		return *x.NextToken
	}
	return ""
}

func (x *ControllerReply) GetVerification() ControllerReply_Verification {
	if x != nil && x.Verification != nil {
		return *x.Verification
	}
	return ControllerReply_UNKNOWN_VERIFICATION
}

// Signature can be added to a request to let it be verfied by the controller
type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the token that was received with the last controller reply
	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	// the PKCS1v15 signature of this message
	Pkcs1V15      []byte `protobuf:"bytes,2,req,name=pkcs1v15" json:"pkcs1v15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_gamecontroller_ssl_gc_rcon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_gamecontroller_ssl_gc_rcon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_gamecontroller_ssl_gc_rcon_proto_rawDescGZIP(), []int{1}
}

func (x *Signature) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *Signature) GetPkcs1V15() []byte {
	if x != nil {
		return x.Pkcs1V15
	}
	return nil
}

var File_gamecontroller_ssl_gc_rcon_proto protoreflect.FileDescriptor

const file_gamecontroller_ssl_gc_rcon_proto_rawDesc = "" +
	"\n" +
	" gamecontroller/ssl_gc_rcon.proto\"\xce\x02\n" +
	"\x0fControllerReply\x12<\n" +
	"\vstatus_code\x18\x01 \x01(\x0e2\x1b.ControllerReply.StatusCodeR\n" +
	"statusCode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"next_token\x18\x03 \x01(\tR\tnextToken\x12A\n" +
	"\fverification\x18\x04 \x01(\x0e2\x1d.ControllerReply.VerificationR\fverification\";\n" +
	"\n" +
	"StatusCode\x12\x17\n" +
	"\x13UNKNOWN_STATUS_CODE\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\"F\n" +
	"\fVerification\x12\x18\n" +
	"\x14UNKNOWN_VERIFICATION\x10\x00\x12\f\n" +
	"\bVERIFIED\x10\x01\x12\x0e\n" +
	"\n" +
	"UNVERIFIED\x10\x02\"=\n" +
	"\tSignature\x12\x14\n" +
	"\x05token\x18\x01 \x02(\tR\x05token\x12\x1a\n" +
	"\bpkcs1v15\x18\x02 \x02(\fR\bpkcs1v15B[B\x0eSslGcRconProtoP\x01ZGgithub.com/RoboCup-SSL/ssl-vision-processor/gui/internal/gamecontroller"

var (
	file_gamecontroller_ssl_gc_rcon_proto_rawDescOnce sync.Once
	file_gamecontroller_ssl_gc_rcon_proto_rawDescData []byte
)

func file_gamecontroller_ssl_gc_rcon_proto_rawDescGZIP() []byte {
	file_gamecontroller_ssl_gc_rcon_proto_rawDescOnce.Do(func() {
		file_gamecontroller_ssl_gc_rcon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_proto_rawDesc)))
	})
	return file_gamecontroller_ssl_gc_rcon_proto_rawDescData
}

var file_gamecontroller_ssl_gc_rcon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gamecontroller_ssl_gc_rcon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gamecontroller_ssl_gc_rcon_proto_goTypes = []any{
	(ControllerReply_StatusCode)(0),   // 0: ControllerReply.StatusCode
	(ControllerReply_Verification)(0), // 1: ControllerReply.Verification
	(*ControllerReply)(nil),           // 2: ControllerReply
	(*Signature)(nil),                 // 3: Signature
}
var file_gamecontroller_ssl_gc_rcon_proto_depIdxs = []int32{
	0, // 0: ControllerReply.status_code:type_name -> ControllerReply.StatusCode
	1, // 1: ControllerReply.verification:type_name -> ControllerReply.Verification
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gamecontroller_ssl_gc_rcon_proto_init() }
func file_gamecontroller_ssl_gc_rcon_proto_init() {
	if File_gamecontroller_ssl_gc_rcon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamecontroller_ssl_gc_rcon_proto_rawDesc), len(file_gamecontroller_ssl_gc_rcon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamecontroller_ssl_gc_rcon_proto_goTypes,
		DependencyIndexes: file_gamecontroller_ssl_gc_rcon_proto_depIdxs,
		EnumInfos:         file_gamecontroller_ssl_gc_rcon_proto_enumTypes,
		MessageInfos:      file_gamecontroller_ssl_gc_rcon_proto_msgTypes,
	}.Build()
	File_gamecontroller_ssl_gc_rcon_proto = out.File
	file_gamecontroller_ssl_gc_rcon_proto_goTypes = nil
	file_gamecontroller_ssl_gc_rcon_proto_depIdxs = nil
}
