// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file vision/ssl_vision_wrapper.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SSL_DetectionFrame, SSL_DetectionFrameJson } from "./ssl_vision_detection_pb";
import { file_vision_ssl_vision_detection } from "./ssl_vision_detection_pb";
import type { SSL_GeometryData, SSL_GeometryDataJson } from "./ssl_vision_geometry_pb";
import { file_vision_ssl_vision_geometry } from "./ssl_vision_geometry_pb";
import type { SSL_VPConfig, SSL_VPConfigJson } from "./ssl_vp_config_pb";
import { file_vision_ssl_vp_config } from "./ssl_vp_config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vision/ssl_vision_wrapper.proto.
 */
export const file_vision_ssl_vision_wrapper: GenFile = /*@__PURE__*/
  fileDesc("Ch92aXNpb24vc3NsX3Zpc2lvbl93cmFwcGVyLnByb3RvIpwBChFTU0xfV3JhcHBlclBhY2tldBImCglkZXRlY3Rpb24YASABKAsyEy5TU0xfRGV0ZWN0aW9uRnJhbWUSIwoIZ2VvbWV0cnkYAiABKAsyES5TU0xfR2VvbWV0cnlEYXRhEhsKBnNvdXJjZRgDIAEoDjILLlNTTF9Tb3VyY2USHQoGY29uZmlnGAQgASgLMg0uU1NMX1ZQQ29uZmlnKqgBCgpTU0xfU291cmNlEhYKElNTTF9TT1VSQ0VfVU5LTk9XThAAEhQKEFNTTF9TT1VSQ0VfT1RIRVIQARIZChVTU0xfU09VUkNFX1NTTF9WSVNJT04QAhIfChtTU0xfU09VUkNFX1ZJU0lPTl9QUk9DRVNTT1IQAxIUChBTU0xfU09VUkNFX0dSU0lNEAQSGgoWU1NMX1NPVVJDRV9FUkZPUkNFX1NJTRAFQlpCFVNzbFZpc2lvbldyYXBwZXJQcm90b1ABWj9naXRodWIuY29tL1JvYm9DdXAtU1NML3NzbC12aXNpb24tcHJvY2Vzc29yL2d1aS9pbnRlcm5hbC92aXNpb24", [file_vision_ssl_vision_detection, file_vision_ssl_vision_geometry, file_vision_ssl_vp_config]);

/**
 * @generated from message SSL_WrapperPacket
 */
export type SSL_WrapperPacket = Message<"SSL_WrapperPacket"> & {
  /**
   * @generated from field: optional SSL_DetectionFrame detection = 1;
   */
  detection?: SSL_DetectionFrame;

  /**
   * @generated from field: optional SSL_GeometryData geometry = 2;
   */
  geometry?: SSL_GeometryData;

  /**
   * @generated from field: optional SSL_Source source = 3;
   */
  source: SSL_Source;

  /**
   * @generated from field: optional SSL_VPConfig config = 4;
   */
  config?: SSL_VPConfig;
};

/**
 * @generated from message SSL_WrapperPacket
 */
export type SSL_WrapperPacketJson = {
  /**
   * @generated from field: optional SSL_DetectionFrame detection = 1;
   */
  detection?: SSL_DetectionFrameJson;

  /**
   * @generated from field: optional SSL_GeometryData geometry = 2;
   */
  geometry?: SSL_GeometryDataJson;

  /**
   * @generated from field: optional SSL_Source source = 3;
   */
  source?: SSL_SourceJson;

  /**
   * @generated from field: optional SSL_VPConfig config = 4;
   */
  config?: SSL_VPConfigJson;
};

/**
 * Describes the message SSL_WrapperPacket.
 * Use `create(SSL_WrapperPacketSchema)` to create a new message.
 */
export const SSL_WrapperPacketSchema: GenMessage<SSL_WrapperPacket, SSL_WrapperPacketJson> = /*@__PURE__*/
  messageDesc(file_vision_ssl_vision_wrapper, 0);

/**
 * @generated from enum SSL_Source
 */
export enum SSL_Source {
  /**
   * @generated from enum value: SSL_SOURCE_UNKNOWN = 0;
   */
  SSL_SOURCE_UNKNOWN = 0,

  /**
   * @generated from enum value: SSL_SOURCE_OTHER = 1;
   */
  SSL_SOURCE_OTHER = 1,

  /**
   * @generated from enum value: SSL_SOURCE_SSL_VISION = 2;
   */
  SSL_SOURCE_SSL_VISION = 2,

  /**
   * @generated from enum value: SSL_SOURCE_VISION_PROCESSOR = 3;
   */
  SSL_SOURCE_VISION_PROCESSOR = 3,

  /**
   * @generated from enum value: SSL_SOURCE_GRSIM = 4;
   */
  SSL_SOURCE_GRSIM = 4,

  /**
   * @generated from enum value: SSL_SOURCE_ERFORCE_SIM = 5;
   */
  SSL_SOURCE_ERFORCE_SIM = 5,
}

/**
 * @generated from enum SSL_Source
 */
export type SSL_SourceJson = "SSL_SOURCE_UNKNOWN" | "SSL_SOURCE_OTHER" | "SSL_SOURCE_SSL_VISION" | "SSL_SOURCE_VISION_PROCESSOR" | "SSL_SOURCE_GRSIM" | "SSL_SOURCE_ERFORCE_SIM";

/**
 * Describes the enum SSL_Source.
 */
export const SSL_SourceSchema: GenEnum<SSL_Source, SSL_SourceJson> = /*@__PURE__*/
  enumDesc(file_vision_ssl_vision_wrapper, 0);

