// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file vision/ssl_vision_wrapper_tracked.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { TrackedFrame, TrackedFrameJson } from "./ssl_vision_detection_tracked_pb";
import { file_vision_ssl_vision_detection_tracked } from "./ssl_vision_detection_tracked_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vision/ssl_vision_wrapper_tracked.proto.
 */
export const file_vision_ssl_vision_wrapper_tracked: GenFile = /*@__PURE__*/
  fileDesc("Cid2aXNpb24vc3NsX3Zpc2lvbl93cmFwcGVyX3RyYWNrZWQucHJvdG8iXwoUVHJhY2tlcldyYXBwZXJQYWNrZXQSDAoEdXVpZBgBIAIoCRITCgtzb3VyY2VfbmFtZRgCIAEoCRIkCg10cmFja2VkX2ZyYW1lGAMgASgLMg0uVHJhY2tlZEZyYW1lQmFCHFNzbFZpc2lvbldyYXBwZXJUcmFja2VkUHJvdG9QAVo/Z2l0aHViLmNvbS9Sb2JvQ3VwLVNTTC9zc2wtdmlzaW9uLXByb2Nlc3Nvci9ndWkvaW50ZXJuYWwvdmlzaW9u", [file_vision_ssl_vision_detection_tracked]);

/**
 * A wrapper packet containing meta data of the source
 * Also serves for the possibility to extend the protocol later
 *
 * @generated from message TrackerWrapperPacket
 */
export type TrackerWrapperPacket = Message<"TrackerWrapperPacket"> & {
  /**
   * A random UUID of the source that is kept constant at the source while running
   * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
   *
   * @generated from field: required string uuid = 1;
   */
  uuid: string;

  /**
   * The name of the source software that is producing this messages.
   *
   * @generated from field: optional string source_name = 2;
   */
  sourceName: string;

  /**
   * The tracked frame
   *
   * @generated from field: optional TrackedFrame tracked_frame = 3;
   */
  trackedFrame?: TrackedFrame;
};

/**
 * A wrapper packet containing meta data of the source
 * Also serves for the possibility to extend the protocol later
 *
 * @generated from message TrackerWrapperPacket
 */
export type TrackerWrapperPacketJson = {
  /**
   * A random UUID of the source that is kept constant at the source while running
   * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
   *
   * @generated from field: required string uuid = 1;
   */
  uuid?: string;

  /**
   * The name of the source software that is producing this messages.
   *
   * @generated from field: optional string source_name = 2;
   */
  sourceName?: string;

  /**
   * The tracked frame
   *
   * @generated from field: optional TrackedFrame tracked_frame = 3;
   */
  trackedFrame?: TrackedFrameJson;
};

/**
 * Describes the message TrackerWrapperPacket.
 * Use `create(TrackerWrapperPacketSchema)` to create a new message.
 */
export const TrackerWrapperPacketSchema: GenMessage<TrackerWrapperPacket, TrackerWrapperPacketJson> = /*@__PURE__*/
  messageDesc(file_vision_ssl_vision_wrapper_tracked, 0);

