// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: vision/ssl_vp_config.proto

package vision

import (
	gamecontroller "github.com/RoboCup-SSL/ssl-vision-processor/gui/internal/gamecontroller"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSL_VPConfigCameraDriver int32

const (
	// FLIR cameras
	SSL_VPConfigCameraDriver_SPINNAKER SSL_VPConfigCameraDriver = 0
	// Video and image files, video4linux2 (e.g. webcams) cameras
	SSL_VPConfigCameraDriver_OPENCV SSL_VPConfigCameraDriver = 1
	// Bluefox3 cameras
	SSL_VPConfigCameraDriver_MVIMPACT SSL_VPConfigCameraDriver = 2
)

// Enum value maps for SSL_VPConfigCameraDriver.
var (
	SSL_VPConfigCameraDriver_name = map[int32]string{
		0: "SPINNAKER",
		1: "OPENCV",
		2: "MVIMPACT",
	}
	SSL_VPConfigCameraDriver_value = map[string]int32{
		"SPINNAKER": 0,
		"OPENCV":    1,
		"MVIMPACT":  2,
	}
)

func (x SSL_VPConfigCameraDriver) Enum() *SSL_VPConfigCameraDriver {
	p := new(SSL_VPConfigCameraDriver)
	*p = x
	return p
}

func (x SSL_VPConfigCameraDriver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSL_VPConfigCameraDriver) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_ssl_vp_config_proto_enumTypes[0].Descriptor()
}

func (SSL_VPConfigCameraDriver) Type() protoreflect.EnumType {
	return &file_vision_ssl_vp_config_proto_enumTypes[0]
}

func (x SSL_VPConfigCameraDriver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SSL_VPConfigCameraDriver) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SSL_VPConfigCameraDriver(num)
	return nil
}

// Deprecated: Use SSL_VPConfigCameraDriver.Descriptor instead.
func (SSL_VPConfigCameraDriver) EnumDescriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{0}
}

type SSL_VPConfigCameraWBType int32

const (
	SSL_VPConfigCameraWBType_OUTDOOR SSL_VPConfigCameraWBType = 0
	SSL_VPConfigCameraWBType_INDOOR  SSL_VPConfigCameraWBType = 1
	SSL_VPConfigCameraWBType_MANUAL  SSL_VPConfigCameraWBType = 2
)

// Enum value maps for SSL_VPConfigCameraWBType.
var (
	SSL_VPConfigCameraWBType_name = map[int32]string{
		0: "OUTDOOR",
		1: "INDOOR",
		2: "MANUAL",
	}
	SSL_VPConfigCameraWBType_value = map[string]int32{
		"OUTDOOR": 0,
		"INDOOR":  1,
		"MANUAL":  2,
	}
)

func (x SSL_VPConfigCameraWBType) Enum() *SSL_VPConfigCameraWBType {
	p := new(SSL_VPConfigCameraWBType)
	*p = x
	return p
}

func (x SSL_VPConfigCameraWBType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSL_VPConfigCameraWBType) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_ssl_vp_config_proto_enumTypes[1].Descriptor()
}

func (SSL_VPConfigCameraWBType) Type() protoreflect.EnumType {
	return &file_vision_ssl_vp_config_proto_enumTypes[1]
}

func (x SSL_VPConfigCameraWBType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SSL_VPConfigCameraWBType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SSL_VPConfigCameraWBType(num)
	return nil
}

// Deprecated: Use SSL_VPConfigCameraWBType.Descriptor instead.
func (SSL_VPConfigCameraWBType) EnumDescriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{1}
}

type SSL_VPConfigStreamType int32

const (
	SSL_VPConfigStreamType_RAW                 SSL_VPConfigStreamType = 0
	SSL_VPConfigStreamType_REPROJ_FALSE_COLOR  SSL_VPConfigStreamType = 1
	SSL_VPConfigStreamType_REPROJ_GRADIENT_DOT SSL_VPConfigStreamType = 2
	SSL_VPConfigStreamType_REPROJ_BLOB_SCORE   SSL_VPConfigStreamType = 3
)

// Enum value maps for SSL_VPConfigStreamType.
var (
	SSL_VPConfigStreamType_name = map[int32]string{
		0: "RAW",
		1: "REPROJ_FALSE_COLOR",
		2: "REPROJ_GRADIENT_DOT",
		3: "REPROJ_BLOB_SCORE",
	}
	SSL_VPConfigStreamType_value = map[string]int32{
		"RAW":                 0,
		"REPROJ_FALSE_COLOR":  1,
		"REPROJ_GRADIENT_DOT": 2,
		"REPROJ_BLOB_SCORE":   3,
	}
)

func (x SSL_VPConfigStreamType) Enum() *SSL_VPConfigStreamType {
	p := new(SSL_VPConfigStreamType)
	*p = x
	return p
}

func (x SSL_VPConfigStreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSL_VPConfigStreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_vision_ssl_vp_config_proto_enumTypes[2].Descriptor()
}

func (SSL_VPConfigStreamType) Type() protoreflect.EnumType {
	return &file_vision_ssl_vp_config_proto_enumTypes[2]
}

func (x SSL_VPConfigStreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SSL_VPConfigStreamType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SSL_VPConfigStreamType(num)
	return nil
}

// Deprecated: Use SSL_VPConfigStreamType.Descriptor instead.
func (SSL_VPConfigStreamType) EnumDescriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{2}
}

type SSL_VPConfigCamera struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Camera driver type. Availability depending on libraries installed.
	Driver *SSL_VPConfigCameraDriver `protobuf:"varint,1,opt,name=driver,enum=SSL_VPConfigCameraDriver" json:"driver,omitempty"`
	// Spinnaker, mvIMPACT or OpenCV(v4l2) camera id
	Id *uint32 `protobuf:"varint,2,opt,name=id,def=0" json:"id,omitempty"`
	// OpenCV camera device, image or video file path (if unset id is used instead)
	Path *string `protobuf:"bytes,3,opt,name=path,def=" json:"path,omitempty"`
	// Camera resolution as reported by the camera. VisionProcessor might use half (true color) resolution internally with SPINNAKER and MVIMPACT.
	// 0 = Highest resolution supported by camera
	Width  *uint32 `protobuf:"varint,4,opt,name=width,def=0" json:"width,omitempty"`
	Height *uint32 `protobuf:"varint,5,opt,name=height,def=0" json:"height,omitempty"`
	// Camera exposure time in ms to adjust brightness. Higher values lead to more motion blur. Lower values lead to a darker image.
	// Camera frame rate will drop if set equal to or higher than the frame time (1 / fps_cam).
	// 0.0 = automatic exposure
	Exposure *float32 `protobuf:"fixed32,6,opt,name=exposure,def=0" json:"exposure,omitempty"`
	// Camera gain to adjust brightness. Higher values lead to more noise. Lower values lead to a darker image.
	// Frequently changing bot identities or team colors indicate an image that is too bright (all colors becoming nearly white).
	// 0.0 = automatic gain
	Gain *float32 `protobuf:"fixed32,7,opt,name=gain,def=0" json:"gain,omitempty"`
	// Camera gamma as nonlinear brightness adjustment. Only supported on SPINNAKER and OPENCV.
	// Low values reduce differences between bright and dark illuminated areas. High values increase the color contrast.
	// 1.0 = no gamma
	Gamma *float32 `protobuf:"fixed32,8,opt,name=gamma,def=1" json:"gamma,omitempty"`
	// Camera white balance. OUTDOOR or INDOOR for auto white balance with green or gray carpet respectively.
	// (distinction between OUTDOOR and INDOOR currently only implemented for SPINNAKER backend)
	WbType        *SSL_VPConfigCameraWBType `protobuf:"varint,9,opt,name=wb_type,json=wbType,enum=SSL_VPConfigCameraWBType,def=0" json:"wb_type,omitempty"`
	WbRed         *float32                  `protobuf:"fixed32,10,opt,name=wb_red,json=wbRed,def=1" json:"wb_red,omitempty"`
	WbBlue        *float32                  `protobuf:"fixed32,11,opt,name=wb_blue,json=wbBlue,def=1" json:"wb_blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for SSL_VPConfigCamera fields.
const (
	Default_SSL_VPConfigCamera_Id       = uint32(0)
	Default_SSL_VPConfigCamera_Path     = string("")
	Default_SSL_VPConfigCamera_Width    = uint32(0)
	Default_SSL_VPConfigCamera_Height   = uint32(0)
	Default_SSL_VPConfigCamera_Exposure = float32(0)
	Default_SSL_VPConfigCamera_Gain     = float32(0)
	Default_SSL_VPConfigCamera_Gamma    = float32(1)
	Default_SSL_VPConfigCamera_WbType   = SSL_VPConfigCameraWBType_OUTDOOR
	Default_SSL_VPConfigCamera_WbRed    = float32(1)
	Default_SSL_VPConfigCamera_WbBlue   = float32(1)
)

func (x *SSL_VPConfigCamera) Reset() {
	*x = SSL_VPConfigCamera{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfigCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfigCamera) ProtoMessage() {}

func (x *SSL_VPConfigCamera) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfigCamera.ProtoReflect.Descriptor instead.
func (*SSL_VPConfigCamera) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{0}
}

func (x *SSL_VPConfigCamera) GetDriver() SSL_VPConfigCameraDriver {
	if x != nil && x.Driver != nil {
		return *x.Driver
	}
	return SSL_VPConfigCameraDriver_SPINNAKER
}

func (x *SSL_VPConfigCamera) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_SSL_VPConfigCamera_Id
}

func (x *SSL_VPConfigCamera) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return Default_SSL_VPConfigCamera_Path
}

func (x *SSL_VPConfigCamera) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return Default_SSL_VPConfigCamera_Width
}

func (x *SSL_VPConfigCamera) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return Default_SSL_VPConfigCamera_Height
}

func (x *SSL_VPConfigCamera) GetExposure() float32 {
	if x != nil && x.Exposure != nil {
		return *x.Exposure
	}
	return Default_SSL_VPConfigCamera_Exposure
}

func (x *SSL_VPConfigCamera) GetGain() float32 {
	if x != nil && x.Gain != nil {
		return *x.Gain
	}
	return Default_SSL_VPConfigCamera_Gain
}

func (x *SSL_VPConfigCamera) GetGamma() float32 {
	if x != nil && x.Gamma != nil {
		return *x.Gamma
	}
	return Default_SSL_VPConfigCamera_Gamma
}

func (x *SSL_VPConfigCamera) GetWbType() SSL_VPConfigCameraWBType {
	if x != nil && x.WbType != nil {
		return *x.WbType
	}
	return Default_SSL_VPConfigCamera_WbType
}

func (x *SSL_VPConfigCamera) GetWbRed() float32 {
	if x != nil && x.WbRed != nil {
		return *x.WbRed
	}
	return Default_SSL_VPConfigCamera_WbRed
}

func (x *SSL_VPConfigCamera) GetWbBlue() float32 {
	if x != nil && x.WbBlue != nil {
		return *x.WbBlue
	}
	return Default_SSL_VPConfigCamera_WbBlue
}

type SSL_VPConfigGeometry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total camera amount over the field
	CameraAmount *uint32 `protobuf:"varint,1,opt,name=camera_amount,json=cameraAmount,def=1" json:"camera_amount,omitempty"`
	// Camera height above field in mm
	// 0.0 = automated camera height calibration, this does not work if the camera looks perpendicular to the field.
	CameraHeight *float32 `protobuf:"fixed32,2,opt,name=camera_height,json=cameraHeight,def=0" json:"camera_height,omitempty"`
	// Field line crossings at the edges of the camera extent in pixels from the top left image corner.
	// The first coordinate must be the edge with the smallest x and y field coordinate.
	LineCorners []*gamecontroller.Vector2 `protobuf:"bytes,3,rep,name=line_corners,json=lineCorners" json:"line_corners,omitempty"`
	// Enable field line pixel refinement.
	// Disable in cluttered environments when the geometry calibration has failed multiple times in a row.
	Refinement    *bool `protobuf:"varint,4,opt,name=refinement,def=1" json:"refinement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for SSL_VPConfigGeometry fields.
const (
	Default_SSL_VPConfigGeometry_CameraAmount = uint32(1)
	Default_SSL_VPConfigGeometry_CameraHeight = float32(0)
	Default_SSL_VPConfigGeometry_Refinement   = bool(true)
)

func (x *SSL_VPConfigGeometry) Reset() {
	*x = SSL_VPConfigGeometry{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfigGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfigGeometry) ProtoMessage() {}

func (x *SSL_VPConfigGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfigGeometry.ProtoReflect.Descriptor instead.
func (*SSL_VPConfigGeometry) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{1}
}

func (x *SSL_VPConfigGeometry) GetCameraAmount() uint32 {
	if x != nil && x.CameraAmount != nil {
		return *x.CameraAmount
	}
	return Default_SSL_VPConfigGeometry_CameraAmount
}

func (x *SSL_VPConfigGeometry) GetCameraHeight() float32 {
	if x != nil && x.CameraHeight != nil {
		return *x.CameraHeight
	}
	return Default_SSL_VPConfigGeometry_CameraHeight
}

func (x *SSL_VPConfigGeometry) GetLineCorners() []*gamecontroller.Vector2 {
	if x != nil {
		return x.LineCorners
	}
	return nil
}

func (x *SSL_VPConfigGeometry) GetRefinement() bool {
	if x != nil && x.Refinement != nil {
		return *x.Refinement
	}
	return Default_SSL_VPConfigGeometry_Refinement
}

type SSL_VPConfigThresholds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum mean cosine similarity (not normalized) of the blob border gradient (0 - 195075.0)
	// High value lead to undetected blobs. Low values lead to an increase in false positive blob detections.
	Circularity *float32 `protobuf:"fixed32,1,opt,name=circularity,def=15" json:"circularity,omitempty"`
	// Minimum circularity/(3*stddev) ball blob score
	Score *float32 `protobuf:"fixed32,2,opt,name=score,def=5" json:"score,omitempty"`
	// Minimum confidence (0.0 - 1.0)
	MinConfidence *float32 `protobuf:"fixed32,3,opt,name=min_confidence,json=minConfidence,def=0.2" json:"min_confidence,omitempty"`
	// Min ball camera edge distance in mm
	MinCamEdgeDistance *float32 `protobuf:"fixed32,4,opt,name=min_cam_edge_distance,json=minCamEdgeDistance,def=170" json:"min_cam_edge_distance,omitempty"`
	// Maximum allowed clipping of two objects in mm
	ClippingTolerance *float32 `protobuf:"fixed32,5,opt,name=clipping_tolerance,json=clippingTolerance,def=10" json:"clipping_tolerance,omitempty"`
	// Added tolerance to geometry related operations in mm.
	// Affects field border cutoff area and field line blob classification.
	GeometryTolerance *float32 `protobuf:"fixed32,6,opt,name=geometry_tolerance,json=geometryTolerance,def=10" json:"geometry_tolerance,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for SSL_VPConfigThresholds fields.
const (
	Default_SSL_VPConfigThresholds_Circularity        = float32(15)
	Default_SSL_VPConfigThresholds_Score              = float32(5)
	Default_SSL_VPConfigThresholds_MinConfidence      = float32(0.20000000298023224)
	Default_SSL_VPConfigThresholds_MinCamEdgeDistance = float32(170)
	Default_SSL_VPConfigThresholds_ClippingTolerance  = float32(10)
	Default_SSL_VPConfigThresholds_GeometryTolerance  = float32(10)
)

func (x *SSL_VPConfigThresholds) Reset() {
	*x = SSL_VPConfigThresholds{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfigThresholds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfigThresholds) ProtoMessage() {}

func (x *SSL_VPConfigThresholds) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfigThresholds.ProtoReflect.Descriptor instead.
func (*SSL_VPConfigThresholds) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{2}
}

func (x *SSL_VPConfigThresholds) GetCircularity() float32 {
	if x != nil && x.Circularity != nil {
		return *x.Circularity
	}
	return Default_SSL_VPConfigThresholds_Circularity
}

func (x *SSL_VPConfigThresholds) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return Default_SSL_VPConfigThresholds_Score
}

func (x *SSL_VPConfigThresholds) GetMinConfidence() float32 {
	if x != nil && x.MinConfidence != nil {
		return *x.MinConfidence
	}
	return Default_SSL_VPConfigThresholds_MinConfidence
}

func (x *SSL_VPConfigThresholds) GetMinCamEdgeDistance() float32 {
	if x != nil && x.MinCamEdgeDistance != nil {
		return *x.MinCamEdgeDistance
	}
	return Default_SSL_VPConfigThresholds_MinCamEdgeDistance
}

func (x *SSL_VPConfigThresholds) GetClippingTolerance() float32 {
	if x != nil && x.ClippingTolerance != nil {
		return *x.ClippingTolerance
	}
	return Default_SSL_VPConfigThresholds_ClippingTolerance
}

func (x *SSL_VPConfigThresholds) GetGeometryTolerance() float32 {
	if x != nil && x.GeometryTolerance != nil {
		return *x.GeometryTolerance
	}
	return Default_SSL_VPConfigThresholds_GeometryTolerance
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           *uint32                `protobuf:"varint,1,opt,name=red,def=128" json:"red,omitempty"`
	Green         *uint32                `protobuf:"varint,2,opt,name=green,def=128" json:"green,omitempty"`
	Blue          *uint32                `protobuf:"varint,3,opt,name=blue,def=128" json:"blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Color fields.
const (
	Default_Color_Red   = uint32(128)
	Default_Color_Green = uint32(128)
	Default_Color_Blue  = uint32(128)
)

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{3}
}

func (x *Color) GetRed() uint32 {
	if x != nil && x.Red != nil {
		return *x.Red
	}
	return Default_Color_Red
}

func (x *Color) GetGreen() uint32 {
	if x != nil && x.Green != nil {
		return *x.Green
	}
	return Default_Color_Green
}

func (x *Color) GetBlue() uint32 {
	if x != nil && x.Blue != nil {
		return *x.Blue
	}
	return Default_Color_Blue
}

type VPColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     *Color                 `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
	Live          *Color                 `protobuf:"bytes,2,opt,name=live" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPColor) Reset() {
	*x = VPColor{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPColor) ProtoMessage() {}

func (x *VPColor) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPColor.ProtoReflect.Descriptor instead.
func (*VPColor) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{4}
}

func (x *VPColor) GetReference() *Color {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *VPColor) GetLive() *Color {
	if x != nil {
		return x.Live
	}
	return nil
}

type SSL_VPConfigColor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Strength of the reference color during color updates (0.0 - 0.5-history_force/2)
	ReferenceForce *float32 `protobuf:"fixed32,1,opt,name=reference_force,json=referenceForce,def=0.1" json:"reference_force,omitempty"`
	// Strength of the previous color during color updates (0.0 - 1.0-reference_force)
	HistoryForce *float32 `protobuf:"fixed32,2,opt,name=history_force,json=historyForce,def=0.7" json:"history_force,omitempty"`
	// Colors used for ball determination
	Orange *VPColor `protobuf:"bytes,3,opt,name=orange" json:"orange,omitempty"`
	Field  *VPColor `protobuf:"bytes,4,opt,name=field" json:"field,omitempty"`
	// Colors used for center blob determination
	Yellow *VPColor `protobuf:"bytes,5,opt,name=yellow" json:"yellow,omitempty"`
	Blue   *VPColor `protobuf:"bytes,6,opt,name=blue" json:"blue,omitempty"`
	// Colors used for side blob determination
	Green         *VPColor `protobuf:"bytes,7,opt,name=green" json:"green,omitempty"`
	Pink          *VPColor `protobuf:"bytes,8,opt,name=pink" json:"pink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for SSL_VPConfigColor fields.
const (
	Default_SSL_VPConfigColor_ReferenceForce = float32(0.10000000149011612)
	Default_SSL_VPConfigColor_HistoryForce   = float32(0.699999988079071)
)

func (x *SSL_VPConfigColor) Reset() {
	*x = SSL_VPConfigColor{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfigColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfigColor) ProtoMessage() {}

func (x *SSL_VPConfigColor) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfigColor.ProtoReflect.Descriptor instead.
func (*SSL_VPConfigColor) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{5}
}

func (x *SSL_VPConfigColor) GetReferenceForce() float32 {
	if x != nil && x.ReferenceForce != nil {
		return *x.ReferenceForce
	}
	return Default_SSL_VPConfigColor_ReferenceForce
}

func (x *SSL_VPConfigColor) GetHistoryForce() float32 {
	if x != nil && x.HistoryForce != nil {
		return *x.HistoryForce
	}
	return Default_SSL_VPConfigColor_HistoryForce
}

func (x *SSL_VPConfigColor) GetOrange() *VPColor {
	if x != nil {
		return x.Orange
	}
	return nil
}

func (x *SSL_VPConfigColor) GetField() *VPColor {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *SSL_VPConfigColor) GetYellow() *VPColor {
	if x != nil {
		return x.Yellow
	}
	return nil
}

func (x *SSL_VPConfigColor) GetBlue() *VPColor {
	if x != nil {
		return x.Blue
	}
	return nil
}

func (x *SSL_VPConfigColor) GetGreen() *VPColor {
	if x != nil {
		return x.Green
	}
	return nil
}

func (x *SSL_VPConfigColor) GetPink() *VPColor {
	if x != nil {
		return x.Pink
	}
	return nil
}

type SSL_VPConfigNetwork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Game controller ip address
	GcIp *string `protobuf:"bytes,1,opt,name=gc_ip,json=gcIp,def=224.5.23.1" json:"gc_ip,omitempty"`
	// Game controller UDP port
	GcPort *uint32 `protobuf:"varint,2,opt,name=gc_port,json=gcPort,def=10003" json:"gc_port,omitempty"`
	// Vision IP address (port impossible to adjust over network)
	VisionIp      *string `protobuf:"bytes,3,opt,name=vision_ip,json=visionIp,def=224.5.23.2" json:"vision_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for SSL_VPConfigNetwork fields.
const (
	Default_SSL_VPConfigNetwork_GcIp     = string("224.5.23.1")
	Default_SSL_VPConfigNetwork_GcPort   = uint32(10003)
	Default_SSL_VPConfigNetwork_VisionIp = string("224.5.23.2")
)

func (x *SSL_VPConfigNetwork) Reset() {
	*x = SSL_VPConfigNetwork{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfigNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfigNetwork) ProtoMessage() {}

func (x *SSL_VPConfigNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfigNetwork.ProtoReflect.Descriptor instead.
func (*SSL_VPConfigNetwork) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{6}
}

func (x *SSL_VPConfigNetwork) GetGcIp() string {
	if x != nil && x.GcIp != nil {
		return *x.GcIp
	}
	return Default_SSL_VPConfigNetwork_GcIp
}

func (x *SSL_VPConfigNetwork) GetGcPort() uint32 {
	if x != nil && x.GcPort != nil {
		return *x.GcPort
	}
	return Default_SSL_VPConfigNetwork_GcPort
}

func (x *SSL_VPConfigNetwork) GetVisionIp() string {
	if x != nil && x.VisionIp != nil {
		return *x.VisionIp
	}
	return Default_SSL_VPConfigNetwork_VisionIp
}

type SSL_VPConfigStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If false no network live stream will be encoded and sent.
	Active *bool `protobuf:"varint,1,opt,name=active,def=1" json:"active,omitempty"`
	// Type of image to transmit.
	Type *SSL_VPConfigStreamType `protobuf:"varint,2,opt,name=type,enum=SSL_VPConfigStreamType,def=0" json:"type,omitempty"`
	// Camera RTP stream destination IP
	StreamIp      *string `protobuf:"bytes,3,opt,name=stream_ip,json=streamIp,def=127.0.0.1" json:"stream_ip,omitempty"`
	StreamPort    *uint32 `protobuf:"varint,4,opt,name=stream_port,json=streamPort,def=10100" json:"stream_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for SSL_VPConfigStream fields.
const (
	Default_SSL_VPConfigStream_Active     = bool(true)
	Default_SSL_VPConfigStream_Type       = SSL_VPConfigStreamType_RAW
	Default_SSL_VPConfigStream_StreamIp   = string("127.0.0.1")
	Default_SSL_VPConfigStream_StreamPort = uint32(10100)
)

func (x *SSL_VPConfigStream) Reset() {
	*x = SSL_VPConfigStream{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfigStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfigStream) ProtoMessage() {}

func (x *SSL_VPConfigStream) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfigStream.ProtoReflect.Descriptor instead.
func (*SSL_VPConfigStream) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{7}
}

func (x *SSL_VPConfigStream) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return Default_SSL_VPConfigStream_Active
}

func (x *SSL_VPConfigStream) GetType() SSL_VPConfigStreamType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_SSL_VPConfigStream_Type
}

func (x *SSL_VPConfigStream) GetStreamIp() string {
	if x != nil && x.StreamIp != nil {
		return *x.StreamIp
	}
	return Default_SSL_VPConfigStream_StreamIp
}

func (x *SSL_VPConfigStream) GetStreamPort() uint32 {
	if x != nil && x.StreamPort != nil {
		return *x.StreamPort
	}
	return Default_SSL_VPConfigStream_StreamPort
}

type SSL_VPConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Persistent human-readable network unique identifier (e.g. hostname or hostname:suffix if multiple VP instances on the same host).
	Instance *string `protobuf:"bytes,1,req,name=instance" json:"instance,omitempty"`
	// Corresponding to the camera_id used in SSL_DetectionFrame. Unique per field and implies position on the field:
	// Single camera field: 0 = global field
	// Double camera field: 0 = -x side, 1 = +x side
	// Quadruple cam field: 0 = -x and -y, 1 = -x and +y, 2 = +x and -y, 3 = +x and +y
	// Configuration for more cams depending on field shape.
	CameraId *uint32 `protobuf:"varint,2,opt,name=camera_id,json=cameraId,def=0" json:"camera_id,omitempty"`
	// Database of SSL game controller team names and robot heights in mm.
	// If the team broadcasted by the game controller has no entry, the average robot height is used.
	RobotHeights map[string]float32      `protobuf:"bytes,3,rep,name=robot_heights,json=robotHeights" json:"robot_heights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Camera       *SSL_VPConfigCamera     `protobuf:"bytes,4,opt,name=camera" json:"camera,omitempty"`
	Geometry     *SSL_VPConfigGeometry   `protobuf:"bytes,5,opt,name=geometry" json:"geometry,omitempty"`
	Thresholds   *SSL_VPConfigThresholds `protobuf:"bytes,6,opt,name=thresholds" json:"thresholds,omitempty"`
	Color        *SSL_VPConfigColor      `protobuf:"bytes,7,opt,name=color" json:"color,omitempty"`
	Network      *SSL_VPConfigNetwork    `protobuf:"bytes,8,opt,name=network" json:"network,omitempty"`
	Stream       *SSL_VPConfigStream     `protobuf:"bytes,9,opt,name=stream" json:"stream,omitempty"`
	// Wait for geometry prior to processing frames
	WaitForGeometry *bool `protobuf:"varint,10,opt,name=wait_for_geometry,json=waitForGeometry,def=0" json:"wait_for_geometry,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for SSL_VPConfig fields.
const (
	Default_SSL_VPConfig_CameraId        = uint32(0)
	Default_SSL_VPConfig_WaitForGeometry = bool(false)
)

func (x *SSL_VPConfig) Reset() {
	*x = SSL_VPConfig{}
	mi := &file_vision_ssl_vp_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSL_VPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSL_VPConfig) ProtoMessage() {}

func (x *SSL_VPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_vision_ssl_vp_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSL_VPConfig.ProtoReflect.Descriptor instead.
func (*SSL_VPConfig) Descriptor() ([]byte, []int) {
	return file_vision_ssl_vp_config_proto_rawDescGZIP(), []int{8}
}

func (x *SSL_VPConfig) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *SSL_VPConfig) GetCameraId() uint32 {
	if x != nil && x.CameraId != nil {
		return *x.CameraId
	}
	return Default_SSL_VPConfig_CameraId
}

func (x *SSL_VPConfig) GetRobotHeights() map[string]float32 {
	if x != nil {
		return x.RobotHeights
	}
	return nil
}

func (x *SSL_VPConfig) GetCamera() *SSL_VPConfigCamera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *SSL_VPConfig) GetGeometry() *SSL_VPConfigGeometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *SSL_VPConfig) GetThresholds() *SSL_VPConfigThresholds {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *SSL_VPConfig) GetColor() *SSL_VPConfigColor {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *SSL_VPConfig) GetNetwork() *SSL_VPConfigNetwork {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SSL_VPConfig) GetStream() *SSL_VPConfigStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *SSL_VPConfig) GetWaitForGeometry() bool {
	if x != nil && x.WaitForGeometry != nil {
		return *x.WaitForGeometry
	}
	return Default_SSL_VPConfig_WaitForGeometry
}

var File_vision_ssl_vp_config_proto protoreflect.FileDescriptor

const file_vision_ssl_vp_config_proto_rawDesc = "" +
	"\n" +
	"\x1avision/ssl_vp_config.proto\x1a$gamecontroller/ssl_gc_geometry.proto\"\xe6\x02\n" +
	"\x12SSL_VPConfigCamera\x121\n" +
	"\x06driver\x18\x01 \x01(\x0e2\x19.SSL_VPConfigCameraDriverR\x06driver\x12\x11\n" +
	"\x02id\x18\x02 \x01(\r:\x010R\x02id\x12\x14\n" +
	"\x04path\x18\x03 \x01(\t:\x00R\x04path\x12\x17\n" +
	"\x05width\x18\x04 \x01(\r:\x010R\x05width\x12\x19\n" +
	"\x06height\x18\x05 \x01(\r:\x010R\x06height\x12\x1d\n" +
	"\bexposure\x18\x06 \x01(\x02:\x010R\bexposure\x12\x15\n" +
	"\x04gain\x18\a \x01(\x02:\x010R\x04gain\x12\x17\n" +
	"\x05gamma\x18\b \x01(\x02:\x011R\x05gamma\x12;\n" +
	"\awb_type\x18\t \x01(\x0e2\x19.SSL_VPConfigCameraWBType:\aOUTDOORR\x06wbType\x12\x18\n" +
	"\x06wb_red\x18\n" +
	" \x01(\x02:\x011R\x05wbRed\x12\x1a\n" +
	"\awb_blue\x18\v \x01(\x02:\x011R\x06wbBlue\"\xb9\x01\n" +
	"\x14SSL_VPConfigGeometry\x12&\n" +
	"\rcamera_amount\x18\x01 \x01(\r:\x011R\fcameraAmount\x12&\n" +
	"\rcamera_height\x18\x02 \x01(\x02:\x010R\fcameraHeight\x12+\n" +
	"\fline_corners\x18\x03 \x03(\v2\b.Vector2R\vlineCorners\x12$\n" +
	"\n" +
	"refinement\x18\x04 \x01(\b:\x04trueR\n" +
	"refinement\"\xb1\x02\n" +
	"\x16SSL_VPConfigThresholds\x12$\n" +
	"\vcircularity\x18\x01 \x01(\x02:\x0215R\vcircularity\x12\x17\n" +
	"\x05score\x18\x02 \x01(\x02:\x015R\x05score\x12:\n" +
	"\x0emin_confidence\x18\x03 \x01(\x02:\x130.20000000298023224R\rminConfidence\x126\n" +
	"\x15min_cam_edge_distance\x18\x04 \x01(\x02:\x03170R\x12minCamEdgeDistance\x121\n" +
	"\x12clipping_tolerance\x18\x05 \x01(\x02:\x0210R\x11clippingTolerance\x121\n" +
	"\x12geometry_tolerance\x18\x06 \x01(\x02:\x0210R\x11geometryTolerance\"R\n" +
	"\x05Color\x12\x15\n" +
	"\x03red\x18\x01 \x01(\r:\x03128R\x03red\x12\x19\n" +
	"\x05green\x18\x02 \x01(\r:\x03128R\x05green\x12\x17\n" +
	"\x04blue\x18\x03 \x01(\r:\x03128R\x04blue\"K\n" +
	"\aVPColor\x12$\n" +
	"\treference\x18\x01 \x01(\v2\x06.ColorR\treference\x12\x1a\n" +
	"\x04live\x18\x02 \x01(\v2\x06.ColorR\x04live\"\xc9\x02\n" +
	"\x11SSL_VPConfigColor\x12<\n" +
	"\x0freference_force\x18\x01 \x01(\x02:\x130.10000000149011612R\x0ereferenceForce\x126\n" +
	"\rhistory_force\x18\x02 \x01(\x02:\x110.699999988079071R\fhistoryForce\x12 \n" +
	"\x06orange\x18\x03 \x01(\v2\b.VPColorR\x06orange\x12\x1e\n" +
	"\x05field\x18\x04 \x01(\v2\b.VPColorR\x05field\x12 \n" +
	"\x06yellow\x18\x05 \x01(\v2\b.VPColorR\x06yellow\x12\x1c\n" +
	"\x04blue\x18\x06 \x01(\v2\b.VPColorR\x04blue\x12\x1e\n" +
	"\x05green\x18\a \x01(\v2\b.VPColorR\x05green\x12\x1c\n" +
	"\x04pink\x18\b \x01(\v2\b.VPColorR\x04pink\"\x7f\n" +
	"\x13SSL_VPConfigNetwork\x12\x1f\n" +
	"\x05gc_ip\x18\x01 \x01(\t:\n" +
	"224.5.23.1R\x04gcIp\x12\x1e\n" +
	"\agc_port\x18\x02 \x01(\r:\x0510003R\x06gcPort\x12'\n" +
	"\tvision_ip\x18\x03 \x01(\t:\n" +
	"224.5.23.2R\bvisionIp\"\xb4\x01\n" +
	"\x12SSL_VPConfigStream\x12\x1c\n" +
	"\x06active\x18\x01 \x01(\b:\x04trueR\x06active\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.SSL_VPConfigStreamType:\x03RAWR\x04type\x12&\n" +
	"\tstream_ip\x18\x03 \x01(\t:\t127.0.0.1R\bstreamIp\x12&\n" +
	"\vstream_port\x18\x04 \x01(\r:\x0510100R\n" +
	"streamPort\"\xa4\x04\n" +
	"\fSSL_VPConfig\x12\x1a\n" +
	"\binstance\x18\x01 \x02(\tR\binstance\x12\x1e\n" +
	"\tcamera_id\x18\x02 \x01(\r:\x010R\bcameraId\x12D\n" +
	"\rrobot_heights\x18\x03 \x03(\v2\x1f.SSL_VPConfig.RobotHeightsEntryR\frobotHeights\x12+\n" +
	"\x06camera\x18\x04 \x01(\v2\x13.SSL_VPConfigCameraR\x06camera\x121\n" +
	"\bgeometry\x18\x05 \x01(\v2\x15.SSL_VPConfigGeometryR\bgeometry\x127\n" +
	"\n" +
	"thresholds\x18\x06 \x01(\v2\x17.SSL_VPConfigThresholdsR\n" +
	"thresholds\x12(\n" +
	"\x05color\x18\a \x01(\v2\x12.SSL_VPConfigColorR\x05color\x12.\n" +
	"\anetwork\x18\b \x01(\v2\x14.SSL_VPConfigNetworkR\anetwork\x12+\n" +
	"\x06stream\x18\t \x01(\v2\x13.SSL_VPConfigStreamR\x06stream\x121\n" +
	"\x11wait_for_geometry\x18\n" +
	" \x01(\b:\x05falseR\x0fwaitForGeometry\x1a?\n" +
	"\x11RobotHeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01*C\n" +
	"\x18SSL_VPConfigCameraDriver\x12\r\n" +
	"\tSPINNAKER\x10\x00\x12\n" +
	"\n" +
	"\x06OPENCV\x10\x01\x12\f\n" +
	"\bMVIMPACT\x10\x02*?\n" +
	"\x18SSL_VPConfigCameraWBType\x12\v\n" +
	"\aOUTDOOR\x10\x00\x12\n" +
	"\n" +
	"\x06INDOOR\x10\x01\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x02*i\n" +
	"\x16SSL_VPConfigStreamType\x12\a\n" +
	"\x03RAW\x10\x00\x12\x16\n" +
	"\x12REPROJ_FALSE_COLOR\x10\x01\x12\x17\n" +
	"\x13REPROJ_GRADIENT_DOT\x10\x02\x12\x15\n" +
	"\x11REPROJ_BLOB_SCORE\x10\x03BUB\x10SslVpConfigProtoP\x01Z?github.com/RoboCup-SSL/ssl-vision-processor/gui/internal/vision"

var (
	file_vision_ssl_vp_config_proto_rawDescOnce sync.Once
	file_vision_ssl_vp_config_proto_rawDescData []byte
)

func file_vision_ssl_vp_config_proto_rawDescGZIP() []byte {
	file_vision_ssl_vp_config_proto_rawDescOnce.Do(func() {
		file_vision_ssl_vp_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vision_ssl_vp_config_proto_rawDesc), len(file_vision_ssl_vp_config_proto_rawDesc)))
	})
	return file_vision_ssl_vp_config_proto_rawDescData
}

var file_vision_ssl_vp_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_vision_ssl_vp_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_vision_ssl_vp_config_proto_goTypes = []any{
	(SSL_VPConfigCameraDriver)(0),  // 0: SSL_VPConfigCameraDriver
	(SSL_VPConfigCameraWBType)(0),  // 1: SSL_VPConfigCameraWBType
	(SSL_VPConfigStreamType)(0),    // 2: SSL_VPConfigStreamType
	(*SSL_VPConfigCamera)(nil),     // 3: SSL_VPConfigCamera
	(*SSL_VPConfigGeometry)(nil),   // 4: SSL_VPConfigGeometry
	(*SSL_VPConfigThresholds)(nil), // 5: SSL_VPConfigThresholds
	(*Color)(nil),                  // 6: Color
	(*VPColor)(nil),                // 7: VPColor
	(*SSL_VPConfigColor)(nil),      // 8: SSL_VPConfigColor
	(*SSL_VPConfigNetwork)(nil),    // 9: SSL_VPConfigNetwork
	(*SSL_VPConfigStream)(nil),     // 10: SSL_VPConfigStream
	(*SSL_VPConfig)(nil),           // 11: SSL_VPConfig
	nil,                            // 12: SSL_VPConfig.RobotHeightsEntry
	(*gamecontroller.Vector2)(nil), // 13: Vector2
}
var file_vision_ssl_vp_config_proto_depIdxs = []int32{
	0,  // 0: SSL_VPConfigCamera.driver:type_name -> SSL_VPConfigCameraDriver
	1,  // 1: SSL_VPConfigCamera.wb_type:type_name -> SSL_VPConfigCameraWBType
	13, // 2: SSL_VPConfigGeometry.line_corners:type_name -> Vector2
	6,  // 3: VPColor.reference:type_name -> Color
	6,  // 4: VPColor.live:type_name -> Color
	7,  // 5: SSL_VPConfigColor.orange:type_name -> VPColor
	7,  // 6: SSL_VPConfigColor.field:type_name -> VPColor
	7,  // 7: SSL_VPConfigColor.yellow:type_name -> VPColor
	7,  // 8: SSL_VPConfigColor.blue:type_name -> VPColor
	7,  // 9: SSL_VPConfigColor.green:type_name -> VPColor
	7,  // 10: SSL_VPConfigColor.pink:type_name -> VPColor
	2,  // 11: SSL_VPConfigStream.type:type_name -> SSL_VPConfigStreamType
	12, // 12: SSL_VPConfig.robot_heights:type_name -> SSL_VPConfig.RobotHeightsEntry
	3,  // 13: SSL_VPConfig.camera:type_name -> SSL_VPConfigCamera
	4,  // 14: SSL_VPConfig.geometry:type_name -> SSL_VPConfigGeometry
	5,  // 15: SSL_VPConfig.thresholds:type_name -> SSL_VPConfigThresholds
	8,  // 16: SSL_VPConfig.color:type_name -> SSL_VPConfigColor
	9,  // 17: SSL_VPConfig.network:type_name -> SSL_VPConfigNetwork
	10, // 18: SSL_VPConfig.stream:type_name -> SSL_VPConfigStream
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_vision_ssl_vp_config_proto_init() }
func file_vision_ssl_vp_config_proto_init() {
	if File_vision_ssl_vp_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vision_ssl_vp_config_proto_rawDesc), len(file_vision_ssl_vp_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vision_ssl_vp_config_proto_goTypes,
		DependencyIndexes: file_vision_ssl_vp_config_proto_depIdxs,
		EnumInfos:         file_vision_ssl_vp_config_proto_enumTypes,
		MessageInfos:      file_vision_ssl_vp_config_proto_msgTypes,
	}.Build()
	File_vision_ssl_vp_config_proto = out.File
	file_vision_ssl_vp_config_proto_goTypes = nil
	file_vision_ssl_vp_config_proto_depIdxs = nil
}
